### ISSUE TITLE
Project does not compile in DEBUG mode

### ISSUE THREAD

**Issue by newsoft** [quarkslab/quarkspwdump#2]
Project compiles cleanly in RELEASE mode, but not in DEBUG mode.

Options to fix in DEBUG configuration, at least:

1/ Use MBCS encoding instead of Unicode.

2/ Add "./include/" as an additional include directory.

3/ Link with ESENT.LIB. Note: this could be set with the following line of code:
# pragma comment(lib, "esent.lib")

**Comment by deesse-k** [comment]
Fixed in last commit.

Thx :)
